application: youtube-player-kit
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /api/[\w\/]+
  script: application.app

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: /favicon.ico
  static_files: www/img/favicon.ico
  upload: www/img/favicon.ico
